// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEEmployee = "e_employee"

// EEmployee mapped from table <e_employee>
type EEmployee struct {
	ID          uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Account     string     `gorm:"column:account;type:varchar(30);not null;uniqueIndex:ACCOUNT_UNIQUE,priority:1" json:"account"`
	Password    *[]byte    `gorm:"column:password;type:binary(32)" json:"password"`
	Nickname    *string    `gorm:"column:nickname;type:varchar(30)" json:"nickname"`
	CreatedAt   time.Time  `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	LastLoginAt *time.Time `gorm:"column:last_login_at;type:datetime" json:"last_login_at"`
}

// TableName EEmployee's table name
func (*EEmployee) TableName() string {
	return TableNameEEmployee
}
