@host = http://127.0.0.1:23456

###
# @add
PUT {{host}}/add HTTP/1.1
Content-Type: application/json

{
    "content": "中文分词测试工具字段",
    "intInfo": 123,
    "floatInfo": 456.789
}

###
# @addBatch
PUT {{host}}/add_batch HTTP/1.1
Content-Type: application/json

[
    {
        "content": "中文分词测试工具3字段",
        "intInfo": 123,
        "floatInfo": 456.789
    },
    {
        "content": "中文分词测试34工具字段",
        "intInfo": 123,
        "floatInfo": 456.789
    },
    {
        "content": "中文分词测试22 工具字段",
        "intInfo": 123,
        "floatInfo": 456.789
    }
]