// Code generated by goctl. DO NOT EDIT.
// Source: grpcdemo.proto

package grpcdemoclient

import (
	"context"

	"grpcdemo/grpcdemo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = grpcdemo.Request
	Response = grpcdemo.Response

	Grpcdemo interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultGrpcdemo struct {
		cli zrpc.Client
	}
)

func NewGrpcdemo(cli zrpc.Client) Grpcdemo {
	return &defaultGrpcdemo{
		cli: cli,
	}
}

func (m *defaultGrpcdemo) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := grpcdemo.NewGrpcdemoClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
