definitions:
  controller.IndexAddParam:
    properties:
      page:
        example: 1
        minimum: 1
        type: integer
      page_size:
        example: 10
        maximum: 20
        minimum: 1
        type: integer
    type: object
  util.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
info:
  contact: {}
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      summary: Show an account
      tags:
      - accounts
  /accounts/add:
    put:
      parameters:
      - example: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - example: 10
        in: query
        maximum: 20
        minimum: 1
        name: page_size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Some Endpoint
  /accounts/delete:
    delete:
      parameters:
      - description: Query Params
        in: body
        name: request
        schema:
          $ref: '#/definitions/controller.IndexAddParam'
      produces:
      - application/json
      responses: {}
      summary: Some Endpoint
  /accounts/list:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      summary: Show an account
      tags:
      - accounts
swagger: "2.0"
