FROM golang:1.16.3 AS builder

COPY ./ /workspace

ENV GOPROXY=https://mirrors.aliyun.com/goproxy/
ENV GO111MODULE=on

RUN cd /workspace && go build -o trial

FROM golang:1.16.3

WORKDIR /app

COPY --from=builder /workspace/trial /app/trial

ENTRYPOINT ["./trial"]
