// Code generated by goctl. DO NOT EDIT.
// Source: grpcdemo.proto

package server

import (
	"context"

	"grpcdemo/grpcdemo"
	"grpcdemo/internal/logic"
	"grpcdemo/internal/svc"
)

type GrpcdemoServer struct {
	svcCtx *svc.ServiceContext
	grpcdemo.UnimplementedGrpcdemoServer
}

func NewGrpcdemoServer(svcCtx *svc.ServiceContext) *GrpcdemoServer {
	return &GrpcdemoServer{
		svcCtx: svcCtx,
	}
}

func (s *GrpcdemoServer) Ping(ctx context.Context, in *grpcdemo.Request) (*grpcdemo.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
