server:
  keepaliveperiodseconds: 0 # keepalive 时间 0 = Go默认(15秒); -1 = 禁用;
  listenaddr: "" # 监听地址, 放空监听所有 0.0.0.0
  port: 80 # HTTP 端口
  ssl:
    enabled: false # true 启用 HTTPS
    redirecttohttps: true # 强制 HTTPS
    listenaddr: "" # 监听地址, 放空监听所有 0.0.0.0
    port: 443 # HTTPS 端口
    certfile: # 证书 (放空使用 letsencrypt)
    certkey: # 证书 key (放空使用 letsencrypt)
    letsencrypt:
      enabled: false # true 从 letsencrypt 申请
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # 申请 letsencrypt 证书的域名列表
  #     - mydomain.tld
  #     - myotherdomain.tld
  responseheaders: # 响应头列表，默认空
  # X-Custom-Header: "custom value"

  cors: # 跨域设置
    alloworigins:
    # - ".+.example.com"
    # - "otherdomain.com"
    allowmethods:
    # - "GET"
    # - "POST"
    allowheaders:
  #   - "Authorization"
  #   - "content-type"

  stream:
    pingperiodseconds: 45 # the interval in which websocket pings will be sent. Only change this value if you know what you are doing.
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed, default only same origin)
#     - ".+.example.com"
#     - "otherdomain.com"
database: # see below
  dialect: sqlite3
  connection: data/gotify.db
defaultuser: # on database creation, gotify creates an admin user (these values will only be used for the first start, if you want to edit the user after the first start use the WebUI)
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: data/images # the directory for storing uploaded images
pluginsdir: data/plugins # the directory where plugin resides (leave empty to disable plugins)
registration: false # enable registrations